In [1]:
import os

from TokenUsage import showTokenUsage
from dotenv import load_dotenv
from GenerateData import generate_basic_data, generate_data_with_ex_vars
from nixtlats import TimeGPT

load_dotenv()

True

In [2]:
timegpt = TimeGPT(token=os.getenv("TIMEGPT_TOKEN"))
timegpt.validate_token()

INFO:nixtlats.timegpt:Happy Forecasting! :), If you have questions or need support, please email ops@nixtla.io

True

In [3]:
showTokenUsage()

Token usage update timed out. There was either no update or the API is down.

TOTAL USAGE: API Calls = 30 | Tokens = 166942 | Spent = 286.85

In [4]:
start = "2023-12-06"
end = "2024-03-04"
low = 75
high = 125

df_basic = generate_basic_data(start, end, low, high)
df_basic

    timestamp       value
0  2023-12-06   95.851100
1  2023-12-07  111.016225
2  2023-12-08   75.005719
3  2023-12-09   90.116629
4  2023-12-10   82.337795
..        ...         ...
85 2024-02-29  119.794311
86 2024-03-01   96.404559
87 2024-03-02  123.242002
88 2024-03-03  108.172075
89 2024-03-04  106.084786

[90 rows x 2 columns]

In [5]:
df_basic_anomalies = timegpt.detect_anomalies(
    df_basic,
    time_col="timestamp",
    target_col="value",
)
df_basic_anomalies

INFO:nixtlats.timegpt:Validating inputs...
INFO:nixtlats.timegpt:Preprocessing dataframes...
INFO:nixtlats.timegpt:Inferred freq: D
INFO:nixtlats.timegpt:Calling Anomaly Detector Endpoint...

     timestamp  anomaly  TimeGPT-lo-99     TimeGPT  TimeGPT-hi-99
0   2024-01-09        0      58.652465   97.411652     136.170838
1   2024-01-10        0      59.382865   98.142052     136.901238
2   2024-01-11        0      61.361053  100.120239     138.879426
3   2024-01-12        0      62.737869  101.497055     140.256242
4   2024-01-13        0      62.357238  101.116425     139.875611
5   2024-01-14        0      61.870414  100.629601     139.388787
6   2024-01-15        0      59.919616   98.678802     137.437989
7   2024-01-16        0      65.394340  104.153526     142.912713
8   2024-01-17        0      64.841460  103.600647     142.359833
9   2024-01-18        0      65.852538  104.611725     143.370911
10  2024-01-19        0      65.467132  104.226318     142.985505
11  2024-01-20        0      65.722106  104.481293     143.240479
12  2024-01-21        0      65.595695  104.354881     143.114068
13  2024-01-22        0      65.296874  104.056061     142.815247
14  2024-01-23        0      62.461280  101.220467     139.979653
15  2024-01-24        0      62.449111  101.208298     139.967484
16  2024-01-25        0      62.261291  101.020477     139.779664
17  2024-01-26        0      61.446716  100.205902     138.965089
18  2024-01-27        0      63.872268  102.631454     141.390641
19  2024-01-28        0      67.902984  106.662170     145.421357
20  2024-01-29        0      64.728484  103.487671     142.246857
21  2024-01-30        0      56.751029   95.510216     134.269402
22  2024-01-31        0      56.374152   95.133339     133.892525
23  2024-02-01        0      56.706741   95.465927     134.225114
24  2024-02-02        0      56.663238   95.422424     134.181611
25  2024-02-03        0      57.210220   95.969406     134.728593
26  2024-02-04        0      59.464927   98.224113     136.983300
27  2024-02-05        0      60.075088   98.834274     137.593461
28  2024-02-06        0      56.519889   95.279076     134.038262
29  2024-02-07        0      56.190643   94.949829     133.709016
30  2024-02-08        0      56.990478   95.749664     134.508851
31  2024-02-09        0      57.455009   96.214195     134.973382
32  2024-02-10        0      57.312476   96.071663     134.830849
33  2024-02-11        0      58.043266   96.802452     135.561639
34  2024-02-12        0      58.797828   97.557014     136.316201
35  2024-02-13        0      62.341300  101.100487     139.859673
36  2024-02-14        0      59.897041   98.656227     137.415414
37  2024-02-15        0      58.941146   97.700333     136.459519
38  2024-02-16        0      61.143348   99.902534     138.661721
39  2024-02-17        0      62.902587  101.661774     140.420960
40  2024-02-18        0      62.885055  101.644241     140.403428
41  2024-02-19        0      62.548049  101.307236     140.066422
42  2024-02-20        0      57.372512   96.131699     134.890885
43  2024-02-21        0      55.811095   94.570282     133.329468
44  2024-02-22        0      52.830512   91.589699     130.348885
45  2024-02-23        0      56.735389   95.494576     134.253762
46  2024-02-24        0      60.769492   99.528679     138.287865
47  2024-02-25        0      59.192298   97.951485     136.710671
48  2024-02-26        0      58.893157   97.652344     136.411530
49  2024-02-27        0      67.823974  106.583160     145.342347
50  2024-02-28        0      65.475532  104.234718     142.993905
51  2024-02-29        0      62.727355  101.486542     140.245728
52  2024-03-01        0      66.595886  105.355072     144.114259
53  2024-03-02        0      71.881339  110.640526     149.399712
54  2024-03-03        0      68.847495  107.606682     146.365868
55  2024-03-04        0      67.636512  106.395699     145.154885

In [6]:
showTokenUsage()

<< Current run: 1 call made | 370 tokens used | 1.00 spent >>

TOTAL USAGE: API Calls = 31 | Tokens = 167312 | Spent = 287.85

In [7]:
df_basic_anomalies_lev75 = timegpt.detect_anomalies(
    df_basic, time_col="timestamp", target_col="value", level=75
)
df_basic_anomalies_lev75

INFO:nixtlats.timegpt:Validating inputs...
INFO:nixtlats.timegpt:Preprocessing dataframes...
INFO:nixtlats.timegpt:Inferred freq: D
INFO:nixtlats.timegpt:Calling Anomaly Detector Endpoint...

     timestamp  anomaly  TimeGPT-lo-75     TimeGPT  TimeGPT-hi-75
0   2024-01-09        0      80.102039   97.411652     114.721264
1   2024-01-10        0      80.832440   98.142052     115.451664
2   2024-01-11        0      82.810627  100.120239     117.429851
3   2024-01-12        0      84.187443  101.497055     118.806667
4   2024-01-13        1      83.806812  101.116425     118.426037
5   2024-01-14        0      83.319988  100.629601     117.939213
6   2024-01-15        1      81.369190   98.678802     115.988415
7   2024-01-16        0      86.843914  104.153526     121.463138
8   2024-01-17        0      86.291035  103.600647     120.910259
9   2024-01-18        0      87.302113  104.611725     121.921337
10  2024-01-19        1      86.916706  104.226318     121.535931
11  2024-01-20        0      87.171681  104.481293     121.790905
12  2024-01-21        0      87.045269  104.354881     121.664493
13  2024-01-22        0      86.746449  104.056061     121.365673
14  2024-01-23        0      83.910854  101.220467     118.530079
15  2024-01-24        1      83.898686  101.208298     118.517910
16  2024-01-25        1      83.710865  101.020477     118.330089
17  2024-01-26        0      82.896290  100.205902     117.515514
18  2024-01-27        0      85.321842  102.631454     119.941067
19  2024-01-28        1      89.352558  106.662170     123.971783
20  2024-01-29        0      86.178059  103.487671     120.797283
21  2024-01-30        1      78.200604   95.510216     112.819828
22  2024-01-31        0      77.823727   95.133339     112.442951
23  2024-02-01        0      78.156315   95.465927     112.775539
24  2024-02-02        0      78.112812   95.422424     112.732036
25  2024-02-03        0      78.659794   95.969406     113.279018
26  2024-02-04        1      80.914501   98.224113     115.533726
27  2024-02-05        0      81.524662   98.834274     116.143886
28  2024-02-06        0      77.969463   95.279076     112.588688
29  2024-02-07        0      77.640217   94.949829     112.259441
30  2024-02-08        1      78.440052   95.749664     113.059276
31  2024-02-09        0      78.904583   96.214195     113.523807
32  2024-02-10        0      78.762051   96.071663     113.381275
33  2024-02-11        0      79.492840   96.802452     114.112064
34  2024-02-12        1      80.247402   97.557014     114.866627
35  2024-02-13        0      83.790875  101.100487     118.410099
36  2024-02-14        1      81.346615   98.656227     115.965839
37  2024-02-15        0      80.390720   97.700333     115.009945
38  2024-02-16        1      82.592922   99.902534     117.212147
39  2024-02-17        0      84.352162  101.661774     118.971386
40  2024-02-18        0      84.334629  101.644241     118.953853
41  2024-02-19        1      83.997624  101.307236     118.616848
42  2024-02-20        1      78.822086   96.131699     113.441311
43  2024-02-21        0      77.260670   94.570282     111.879894
44  2024-02-22        1      74.280087   91.589699     108.899311
45  2024-02-23        0      78.184963   95.494576     112.804188
46  2024-02-24        1      82.219067   99.528679     116.838291
47  2024-02-25        0      80.641873   97.951485     115.261097
48  2024-02-26        0      80.342732   97.652344     114.961956
49  2024-02-27        0      89.273548  106.583160     123.892773
50  2024-02-28        0      86.925106  104.234718     121.544330
51  2024-02-29        1      84.176930  101.486542     118.796154
52  2024-03-01        0      88.045460  105.355072     122.664684
53  2024-03-02        0      93.330914  110.640526     127.950138
54  2024-03-03        0      90.297070  107.606682     124.916294
55  2024-03-04        0      89.086086  106.395699     123.705311

In [8]:
showTokenUsage()

<< Current run: 1 call made | 370 tokens used | 1.00 spent >>

TOTAL USAGE: API Calls = 32 | Tokens = 167682 | Spent = 288.85

In [9]:
df_basic_anomalies_lev50_plus_date_features = timegpt.detect_anomalies(
    df_basic, time_col="timestamp", target_col="value", level=50, date_features=True
)
df_basic_anomalies_lev50_plus_date_features

INFO:nixtlats.timegpt:Validating inputs...
INFO:nixtlats.timegpt:Preprocessing dataframes...
INFO:nixtlats.timegpt:Inferred freq: D
INFO:nixtlats.timegpt:Calling Anomaly Detector Endpoint...
INFO:nixtlats.timegpt:Using the following exogenous variables: year_2023, year_2024, month_1, month_2, month_3, month_12, day_1, day_2, day_3, day_4, day_5, day_6, day_7, day_8, day_9, day_10, day_11, day_12, day_13, day_14, day_15, day_16, day_17, day_18, day_19, day_20, day_21, day_22, day_23, day_24, day_25, day_26, day_27, day_28, day_29, day_30, day_31, weekday_0, weekday_1, weekday_2, weekday_3, weekday_4, weekday_5, weekday_6

     timestamp  anomaly  TimeGPT-lo-50     TimeGPT  TimeGPT-hi-50
0   2024-01-09        1      84.523922   94.763239     105.002556
1   2024-01-10        0      85.026257   95.265574     105.504891
2   2024-01-11        1      86.881479   97.120796     107.360114
3   2024-01-12        1      88.164198   98.403515     108.642832
4   2024-01-13        1      88.097826   98.337143     108.576460
5   2024-01-14        1      87.663904   97.903221     108.142539
6   2024-01-15        1      85.432688   95.672005     105.911322
7   2024-01-16        0      94.132763  104.372080     114.611397
8   2024-01-17        1      93.304249  103.543566     113.782883
9   2024-01-18        1      93.775497  104.014815     114.254132
10  2024-01-19        1      93.499073  103.738390     113.977707
11  2024-01-20        0      93.649818  103.889136     114.128453
12  2024-01-21        1      93.897934  104.137251     114.376568
13  2024-01-22        1      93.865383  104.104700     114.344018
14  2024-01-23        1      90.444159  100.683476     110.922793
15  2024-01-24        1      90.349711  100.589028     110.828345
16  2024-01-25        1      89.874100  100.113417     110.352734
17  2024-01-26        0      88.893309   99.132626     109.371943
18  2024-01-27        1      91.208157  101.447474     111.686791
19  2024-01-28        1      95.535706  105.775023     116.014340
20  2024-01-29        0      92.738161  102.977478     113.216795
21  2024-01-30        1      85.270895   95.510212     105.749529
22  2024-01-31        0      84.894024   95.133341     105.372658
23  2024-02-01        1      92.977427  103.216744     113.456061
24  2024-02-02        0      92.933921  103.173238     113.412555
25  2024-02-03        0      93.480904  103.720221     113.959539
26  2024-02-04        1      95.735612  105.974929     116.214246
27  2024-02-05        1      96.345772  106.585090     116.824407
28  2024-02-06        0      89.472321   99.711638     109.950956
29  2024-02-07        0      89.285315   99.524632     109.763950
30  2024-02-08        1      89.819632  100.058949     110.298267
31  2024-02-09        0      90.203530  100.442847     110.682164
32  2024-02-10        0      90.143553  100.382871     110.622188
33  2024-02-11        0      90.931262  101.170579     111.409896
34  2024-02-12        1      91.867924  102.107242     112.346559
35  2024-02-13        0      93.479216  103.718533     113.957851
36  2024-02-14        1      91.169726  101.409043     111.648360
37  2024-02-15        1      90.021231  100.260548     110.499866
38  2024-02-16        1      92.229388  102.468705     112.708022
39  2024-02-17        1      94.240994  104.480311     114.719628
40  2024-02-18        0      94.153279  104.392596     114.631913
41  2024-02-19        1      94.045613  104.284930     114.524247
42  2024-02-20        1      87.661177   97.900494     108.139812
43  2024-02-21        0      86.212123   96.451440     106.690757
44  2024-02-22        1      83.183368   93.422686     103.662003
45  2024-02-23        1      86.411990   96.651307     106.890624
46  2024-02-24        1      90.471297  100.710614     110.949931
47  2024-02-25        0      89.400334   99.639651     109.878968
48  2024-02-26        1      89.406405   99.645722     109.885039
49  2024-02-27        1      96.963763  107.203080     117.442397
50  2024-02-28        1      94.421363  104.660680     114.899997
51  2024-02-29        1      91.198773  101.438090     111.677407
52  2024-03-01        1      96.581793  106.821111     117.060428
53  2024-03-02        1     101.891039  112.130357     122.369674
54  2024-03-03        0      99.307181  109.546498     119.785815
55  2024-03-04        0      98.380471  108.619788     118.859105

In [10]:
showTokenUsage()

<< Current run: 1 call made | 4330 tokens used | 5.76 spent >>

TOTAL USAGE: API Calls = 33 | Tokens = 172012 | Spent = 294.61

In [11]:
start = "2023-12-06"
end = "2024-03-04"
low_val = 75
high_val = 125
ex_vars_count = 2
ex_vars_low = 10
ex_vars_high = 20

df_ex_vars = generate_data_with_ex_vars(
    start, end, low_val, high_val, ex_vars_count, ex_vars_low, ex_vars_high
)
df_ex_vars

    timestamp       value   ex_var_1   ex_var_2
0  2023-12-06   95.851100  11.147460  16.297175
1  2023-12-07  111.016225  19.494893  12.101740
2  2023-12-08   75.005719  14.499121  17.527556
3  2023-12-09   90.116629  15.783896  10.665365
4  2023-12-10   82.337795  14.081368  12.603151
..        ...         ...        ...        ...
85 2024-02-29  119.794311  17.453344  13.226810
86 2024-03-01   96.404559  16.692329  16.707888
87 2024-03-02  123.242002  12.649196  14.508739
88 2024-03-03  108.172075  10.663348  13.821028
89 2024-03-04  106.084786  13.700842  14.108113

[90 rows x 4 columns]

In [12]:
df_ex_vars_anomalies = timegpt.detect_anomalies(
    df_ex_vars,
    time_col="timestamp",
    target_col="value",
)
df_ex_vars_anomalies

INFO:nixtlats.timegpt:Validating inputs...
INFO:nixtlats.timegpt:Preprocessing dataframes...
INFO:nixtlats.timegpt:Inferred freq: D
INFO:nixtlats.timegpt:Calling Anomaly Detector Endpoint...
INFO:nixtlats.timegpt:Using the following exogenous variables: ex_var_1, ex_var_2

     timestamp  anomaly  TimeGPT-lo-99     TimeGPT  TimeGPT-hi-99
0   2024-01-09        0      63.835697   98.827587     133.819477
1   2024-01-10        0      70.720385  105.712275     140.704165
2   2024-01-11        0      63.834346   98.826237     133.818127
3   2024-01-12        0      65.219568  100.211458     135.203349
4   2024-01-13        0      60.408860   95.400750     130.392640
5   2024-01-14        0      67.308651  102.300541     137.292431
6   2024-01-15        0      76.773871  111.765761     146.757651
7   2024-01-16        0      69.170417  104.162308     139.154198
8   2024-01-17        0      80.421551  115.413441     150.405332
9   2024-01-18        0      62.554635   97.546525     132.538415
10  2024-01-19        0      72.138797  107.130688     142.122578
11  2024-01-20        0      72.226151  107.218042     142.209932
12  2024-01-21        0      74.076830  109.068721     144.060611
13  2024-01-22        0      67.440324  102.432215     137.424105
14  2024-01-23        0      62.244425   97.236315     132.228205
15  2024-01-24        0      62.568512   97.560402     132.552292
16  2024-01-25        0      63.870148   98.862038     133.853929
17  2024-01-26        0      72.685283  107.677174     142.669064
18  2024-01-27        0      64.006524   98.998414     133.990305
19  2024-01-28        0      68.022376  103.014267     138.006157
20  2024-01-29        0      73.527189  108.519079     143.510970
21  2024-01-30        0      54.701768   89.693658     124.685549
22  2024-01-31        0      63.685702   98.677592     133.669483
23  2024-02-01        0      64.327960   99.319850     134.311740
24  2024-02-02        0      59.172341   94.164231     129.156121
25  2024-02-03        0      57.903642   92.895532     127.887422
26  2024-02-04        0      60.533300   95.525190     130.517080
27  2024-02-05        0      60.379921   95.371811     130.363701
28  2024-02-06        0      75.344574  110.336465     145.328355
29  2024-02-07        0      56.597541   91.589431     126.581322
30  2024-02-08        0      64.032712   99.024602     134.016492
31  2024-02-09        0      60.114401   95.106291     130.098181
32  2024-02-10        0      60.032674   95.024564     130.016455
33  2024-02-11        0      74.709956  109.701847     144.693737
34  2024-02-12        0      62.667096   97.658987     132.650877
35  2024-02-13        0      62.388265   97.380156     132.372046
36  2024-02-14        0      67.034785  102.026675     137.018566
37  2024-02-15        0      59.665397   94.657287     129.649178
38  2024-02-16        0      63.098147   98.090038     133.081928
39  2024-02-17        0      63.976826   98.968716     133.960606
40  2024-02-18        0      61.425468   96.417358     131.409248
41  2024-02-19        0      57.321179   92.313069     127.304960
42  2024-02-20        0      71.053640  106.045531     141.037421
43  2024-02-21        0      58.164430   93.156321     128.148211
44  2024-02-22        0      67.477007  102.468897     137.460788
45  2024-02-23        0      76.977902  111.969792     146.961682
46  2024-02-24        0      68.705748  103.697639     138.689529
47  2024-02-25        0      62.364544   97.356434     132.348324
48  2024-02-26        0      69.898524  104.890414     139.882305
49  2024-02-27        0      69.877997  104.869888     139.861778
50  2024-02-28        0      64.469154   99.461044     134.452934
51  2024-02-29        0      60.165323   95.157213     130.149103
52  2024-03-01        0      60.649651   95.641541     130.633432
53  2024-03-02        0      81.605350  116.597241     151.589131
54  2024-03-03        0      69.185879  104.177769     139.169660
55  2024-03-04        0      67.539590  102.531480     137.523371

In [13]:
showTokenUsage()

<< Current run: 1 call made | 550 tokens used | 1.22 spent >>

TOTAL USAGE: API Calls = 34 | Tokens = 172562 | Spent = 295.83

In [14]:
df_ex_vars_anomalies_lev75 = timegpt.detect_anomalies(
    df_ex_vars, time_col="timestamp", target_col="value", level=75
)
df_ex_vars_anomalies_lev75

INFO:nixtlats.timegpt:Validating inputs...
INFO:nixtlats.timegpt:Preprocessing dataframes...
INFO:nixtlats.timegpt:Inferred freq: D
INFO:nixtlats.timegpt:Calling Anomaly Detector Endpoint...
INFO:nixtlats.timegpt:Using the following exogenous variables: ex_var_1, ex_var_2

     timestamp  anomaly  TimeGPT-lo-75     TimeGPT  TimeGPT-hi-75
0   2024-01-09        0      83.200426   98.827587     114.454748
1   2024-01-10        0      90.085114  105.712275     121.339436
2   2024-01-11        0      83.199076   98.826237     114.453398
3   2024-01-12        1      84.584297  100.211458     115.838619
4   2024-01-13        1      79.773589   95.400750     111.027911
5   2024-01-14        0      86.673380  102.300541     117.927702
6   2024-01-15        0      96.138600  111.765761     127.392922
7   2024-01-16        0      88.535147  104.162308     119.789469
8   2024-01-17        1      99.786280  115.413441     131.040602
9   2024-01-18        1      81.919364   97.546525     113.173686
10  2024-01-19        1      91.503527  107.130688     122.757849
11  2024-01-20        0      91.590881  107.218042     122.845203
12  2024-01-21        0      93.441560  109.068721     124.695882
13  2024-01-22        0      86.805053  102.432215     118.059376
14  2024-01-23        0      81.609154   97.236315     112.863476
15  2024-01-24        1      81.933241   97.560402     113.187563
16  2024-01-25        1      83.234877   98.862038     114.489199
17  2024-01-26        0      92.050013  107.677174     123.304335
18  2024-01-27        0      83.371253   98.998414     114.625575
19  2024-01-28        0      87.387106  103.014267     118.641428
20  2024-01-29        0      92.891918  108.519079     124.146240
21  2024-01-30        0      74.066497   89.693658     105.320819
22  2024-01-31        0      83.050431   98.677592     114.304753
23  2024-02-01        1      83.692689   99.319850     114.947011
24  2024-02-02        0      78.537070   94.164231     109.791392
25  2024-02-03        1      77.268371   92.895532     108.522693
26  2024-02-04        0      79.898029   95.525190     111.152351
27  2024-02-05        0      79.744650   95.371811     110.998972
28  2024-02-06        0      94.709303  110.336465     125.963626
29  2024-02-07        0      75.962270   91.589431     107.216592
30  2024-02-08        1      83.397441   99.024602     114.651763
31  2024-02-09        0      79.479130   95.106291     110.733452
32  2024-02-10        0      79.397403   95.024564     110.651725
33  2024-02-11        0      94.074686  109.701847     125.329008
34  2024-02-12        1      82.031826   97.658987     113.286148
35  2024-02-13        0      81.752995   97.380156     113.007317
36  2024-02-14        1      86.399514  102.026675     117.653836
37  2024-02-15        0      79.030126   94.657287     110.284448
38  2024-02-16        1      82.462877   98.090038     113.717199
39  2024-02-17        1      83.341555   98.968716     114.595877
40  2024-02-18        0      80.790197   96.417358     112.044519
41  2024-02-19        0      76.685908   92.313069     107.940230
42  2024-02-20        0      90.418370  106.045531     121.672692
43  2024-02-21        0      77.529159   93.156321     108.783482
44  2024-02-22        0      86.841736  102.468897     118.096059
45  2024-02-23        0      96.342631  111.969792     127.596953
46  2024-02-24        0      88.070478  103.697639     119.324800
47  2024-02-25        0      81.729273   97.356434     112.983595
48  2024-02-26        0      89.263253  104.890414     120.517576
49  2024-02-27        0      89.242727  104.869888     120.497049
50  2024-02-28        0      83.833883   99.461044     115.088205
51  2024-02-29        1      79.530052   95.157213     110.784374
52  2024-03-01        0      80.014380   95.641541     111.268702
53  2024-03-02        0     100.970079  116.597241     132.224402
54  2024-03-03        0      88.550608  104.177769     119.804930
55  2024-03-04        0      86.904319  102.531480     118.158641

In [15]:
showTokenUsage()

<< Current run: 1 call made | 550 tokens used | 1.22 spent >>

TOTAL USAGE: API Calls = 35 | Tokens = 173112 | Spent = 297.05

In [16]:
df_ex_vars_anomalies_lev50_plus_date_features = timegpt.detect_anomalies(
    df_ex_vars, time_col="timestamp", target_col="value", level=50, date_features=True
)
df_ex_vars_anomalies_lev50_plus_date_features

INFO:nixtlats.timegpt:Validating inputs...
INFO:nixtlats.timegpt:Preprocessing dataframes...
INFO:nixtlats.timegpt:Inferred freq: D
INFO:nixtlats.timegpt:Calling Anomaly Detector Endpoint...
INFO:nixtlats.timegpt:Using the following exogenous variables: ex_var_1, ex_var_2, year_2023, year_2024, month_1, month_2, month_3, month_12, day_1, day_2, day_3, day_4, day_5, day_6, day_7, day_8, day_9, day_10, day_11, day_12, day_13, day_14, day_15, day_16, day_17, day_18, day_19, day_20, day_21, day_22, day_23, day_24, day_25, day_26, day_27, day_28, day_29, day_30, day_31, weekday_0, weekday_1, weekday_2, weekday_3, weekday_4, weekday_5, weekday_6

     timestamp  anomaly  TimeGPT-lo-50     TimeGPT  TimeGPT-hi-50
0   2024-01-09        1      88.672430   97.879491     107.086551
1   2024-01-10        1      93.405627  102.612688     111.819749
2   2024-01-11        1      88.254636   97.461697     106.668758
3   2024-01-12        1      87.599618   96.806679     106.013739
4   2024-01-13        1      86.493156   95.700217     104.907278
5   2024-01-14        1      90.320702   99.527763     108.734824
6   2024-01-15        1      98.380142  107.587203     116.794264
7   2024-01-16        0      95.675192  104.882252     114.089313
8   2024-01-17        1     103.799984  113.007045     122.214105
9   2024-01-18        1      90.472362   99.679423     108.886484
10  2024-01-19        1      97.704046  106.911107     116.118168
11  2024-01-20        1      98.604238  107.811299     117.018360
12  2024-01-21        1      95.705069  104.912130     114.119191
13  2024-01-22        1      92.371896  101.578957     110.786018
14  2024-01-23        0      86.729987   95.937048     105.144109
15  2024-01-24        1      87.060620   96.267681     105.474742
16  2024-01-25        1      86.710540   95.917601     105.124662
17  2024-01-26        0      97.458312  106.665372     115.872433
18  2024-01-27        1      90.271337   99.478398     108.685458
19  2024-01-28        1      92.738345  101.945406     111.152467
20  2024-01-29        0      98.640271  107.847332     117.054392
21  2024-01-30        1      82.892688   92.099749     101.306810
22  2024-01-31        0      89.728717   98.935778     108.142839
23  2024-02-01        1      96.020682  105.227743     114.434804
24  2024-02-02        0      91.885075  101.092136     110.299196
25  2024-02-03        1      89.019503   98.226564     107.433625
26  2024-02-04        1      93.288657  102.495718     111.702779
27  2024-02-05        0      92.704987  101.912048     111.119109
28  2024-02-06        0     104.531530  113.738591     122.945652
29  2024-02-07        0      87.509588   96.716648     105.923709
30  2024-02-08        1      92.529912  101.736973     110.944034
31  2024-02-09        0      86.083344   95.290405     104.497466
32  2024-02-10        1      89.562778   98.769839     107.976899
33  2024-02-11        1     103.987786  113.194846     122.401907
34  2024-02-12        1      91.164695  100.371756     109.578816
35  2024-02-13        0      90.526990   99.734051     108.941111
36  2024-02-14        1      95.810780  105.017840     114.224901
37  2024-02-15        1      86.084350   95.291410     104.498471
38  2024-02-16        1      93.057347  102.264408     111.471468
39  2024-02-17        1      91.870151  101.077211     110.284272
40  2024-02-18        0      88.016348   97.223409     106.430470
41  2024-02-19        1      86.476571   95.683632     104.890693
42  2024-02-20        1      97.367417  106.574478     115.781539
43  2024-02-21        0      83.291757   92.498818     101.705879
44  2024-02-22        0      98.246627  107.453688     116.660748
45  2024-02-23        0     103.352211  112.559271     121.766332
46  2024-02-24        1      92.302078  101.509138     110.716199
47  2024-02-25        0      89.160344   98.367405     107.574466
48  2024-02-26        0      94.856359  104.063420     113.270481
49  2024-02-27        1      93.621594  102.828655     112.035716
50  2024-02-28        1      91.086935  100.293996     109.501057
51  2024-02-29        1      89.272930   98.479991     107.687052
52  2024-03-01        0      84.840328   94.047389     103.254450
53  2024-03-02        0     106.601332  115.808392     125.015453
54  2024-03-03        0      95.508742  104.715803     113.922864
55  2024-03-04        0      93.736342  102.943403     112.150464

In [17]:
showTokenUsage()

<< Current run: 1 call made | 4510 tokens used | 5.97 spent >>

TOTAL USAGE: API Calls = 36 | Tokens = 177622 | Spent = 303.02